server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      client:
        enabled: true #设置开启请求跟踪（默认true）
    sampler:
      probability: 1.0 #设置采样比例（默认1.0）
  zipkin:
    base-url: http://localhost:9090/ #配置zipkin server的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #配置注册中心的地址